<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 27/12/2019
 * Time: 16:43
 */
?>

<h1>Elements du forum</h1>

<ul>
    <?php foreach($forum->getTopics() as $topic): ?>

        <li>
            <a href="<?= $this->url('forums/topic', ['id_forum'=>$topic->getForum()->getId(), 'id'=>$topic->getId() ]);?>">
                <?= $topic->getName(); ?>
            </a>
        </li>

    <?php endforeach; ?>
</ul>
