<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 27/12/2019
 * Time: 16:43
 */
?>

<h1>Elements du sujet</h1>

    <?php foreach($subject->getPosts() as $post): ?>

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-3">
                        <p class="card-text">Ici se trouveront les informations sur l'utilisateur</p>
                    </div>
                    <div class="col-lg-9">
                        <p class="card-text"><?= $post->getContent(); ?></p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <?= $post->getDateCreate()->format('d/m/Y \à H:i'); ?>
            </div>
        </div>
    <?php endforeach; ?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('content')); ?>
    <?= $this->formElement($form->get('content')); ?>
    <?= $this->formElementErrors($form->get('content')); ?>
</div>


<?= $this->formElement($form->get('csrf')); ?>

<?= $this->formElement($form->get('submit')); ?>

<?= $this->form()->closeTag(); ?>
